language: java
jdk:
  - oraclejdk8
os:
  - linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t antoineaumjaud/api-home-security:latest .;
    docker push antoineaumjaud/api-home-security;
    fi

notifications:
  email: 
    on_failure: always
    on_sucess: never
  webhooks:
    urls:
      - https://api-synology-chatbot.aumjaud.fr/send-travis/continuous-integration
    on_success: always
    on_failure: always
